name: Workflow push
on: 
    pull_request: 
      branches:
        - main
jobs:
    tests-unitaires:
        runs-on: windows-latest
        steps: 
          - name: Récupération du repo
            uses: actions/checkout@v2
          - name: Récupération de nodejs
            uses: actions/setup-node@v2
            with: 
                node-version: '16'
          - run: npm install
          - run: npm test
    build: 
        needs: tests-unitaires
        runs-on: windows-latest
        steps: 
          - name: Récupération du rep
            uses: actions/checkout@v2
          - name: Récupération de nodejs
            uses: actions/setup-node@v2
            with: 
                node-version: '16'

