name: Workflow push
on: 
    pull_request: 
      branches:
        - main
jobs:
    tests-unitaires:
      runs-on: windows-latest
      steps: 
        - name: Récupération du repo
          uses: actions/checkout@v2
        - name: Récupération de nodejs
          uses: actions/setup-node@v2
          with: 
              node-version: '16'
        - run: npm install
        - run: npm test
    docker: 
      needs: build
      runs-on: windows-latest
      steps:
        - name: Récupération du repo
          uses: actions/checkout@v2
        - name: Récupération de nodejs
          uses: actions/setup-node@v2
          with: 
              node-version: '16'
        - name: Installation de QEMU Docker
          uses: docker/setup-qemu-action@v1
        - name: Installation de  BuildX Docker
          uses: docker/setup-buildx-action@v1
        - name: Connection à Docker
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        - name: Build et push de l'image Docker
          uses: docker/build-push-action@v2
            with:
              context: .
              push: true
              tags: bbmt10/weather:latest

        


